palette:
  top: '#024700'
  bottom: '#000000'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#d0d0d0'
  footer: '#161617'
  titleslogan: '#ffffff'
  text: '#3b3b3b'
  link: '#0073b6'
logo: 'public://color/proto-41df5beb/logo.svg'
stylesheets:
  - 'public://color/proto-41df5beb/colors.css'
files:
  - 'public://color/proto-41df5beb/logo.svg'
  - 'public://color/proto-41df5beb/colors.css'
